spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/learning_system
    username: postgres
    password: 123
  jpa:
    hibernate:
      ddl-auto: validate

jwt:
  secret: MegaLargeSigningSecretKeyForDemoApplicationMegaLargeSigningSecretKeyForDemoApplication
  expiration: 86400000